id: A2087B393
base_file: f1717.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:14:32.953664
  last_modified_at: 2022-06-05 20:14:32.953673
