id: A2087B393
base_file: fCC07.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:14:32.956240
  last_modified_at: 2022-06-05 20:14:32.956246
